### ISSUE TITLE
Make project more configurable / re-usable

### ISSUE THREAD

**Issue by emmenko** [commercetools/sphere-donut#7]
It's really hard to re-use this project for a couple of reasons:
- stuff is hardcoded (e.g.: https://github.com/commercetools/sphere-donut/blob/master/app/utils/Util.java#L11). If I have different products I can't do anything with the current implementation
- as an external developer I don't have access to the project / product data, which makes it really hard to understand how it works since the implementation assumes there are particular attributes, variants, images, ...
- pactas / paymill should be optional

**Comment by lauraluiz** [comment]
In fact I already started long time ago to re-implement the project to allow all what you mention and some more. I started with improving the Pactas: https://github.com/commercetools/sphere-donut/tree/pactas-improve

But as I'm working on my "free time" since this shop is not a priority, that's been a bit delayed :)
If we are using it now, I can move the priority behind Sunrise.

**Comment by emmenko** [comment]
There was a use case in the hackathon, but was so complicated to refactor it that we had to drop it.

**Comment by lauraluiz** [comment]
https://github.com/commercetools/sphere-donut/issues/21

**Comment by lauraluiz** [comment]
In progress
